ScheduleProg/Models/PareSubgroup.cs
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
namespace ScheduleProg.Models
{
    public class PareSubgroup
    {
        public int Pare_Id { get; set; }
       

        public int Subgroup_Id{ get; set; }

     
        [ValidateNever]
        public Pare Pare { get; set; }
        [ValidateNever]
        public Subgroup Subgroup { get; set; }
    }
}

ScheduleProg/Controllers/PareSubgroupsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ScheduleProg.Data;
using ScheduleProg.Models;

namespace ScheduleProg.Controllers
{
    [Authorize(Roles = "Адміністратор")]
    public class PareSubgroupsController : Controller
    {
        private readonly ApplicationDbContext _context;
        
        public PareSubgroupsController(ApplicationDbContext context)
        {
            _context = context;
        }

        [HttpGet]
        public  IActionResult Index()
        {
            /*var applicationDbContext = _context.PareSubgroups.Include(p => p.Pare).Include(p => p.Subgroup);
            return View(await applicationDbContext.ToListAsync());*/
            return View();
        }
       
        public async Task<IActionResult> AdminView()
        {
            var applicationDbContext = _context.PareSubgroups.Include(p => p.Pare).Include(p => p.Subgroup);
            return View(await applicationDbContext.ToListAsync());
        }
        // GET: PareSubgroups

        /*public async Task<IActionResult> Index(string WeekDay)
        {
            *//*var applicationDbContext = _context.PareSubgroups.Include(p => p.Pare).Include(p => p.Subgroup);
            return View(await applicationDbContext.ToListAsync());*//*
            return Create(WeekDay);
        }*/

        // GET: PareSubgroups/Details/5
        
       

        public async Task<IActionResult> GetDay(string WeekDay) {

            return Create(WeekDay);
        }
        [HttpGet]
        // GET: PareSubgroups/Create
        public IActionResult Create(string Week_Day)
        {
            //var result =_context.Schedules.FromSqlRaw("Select * from Pare where Teacher_Id=2").ToList();
            ViewData["Pare_Id"] = new SelectList(_context.Schedules
                .Include(s => s.Subject)
                .Include(s => s.PairTime)
                .Where(s=>s.Week_Day== Week_Day)
                .Where(s=>s.Pair_Time_Id==1)
                , "Id", "Description");
            ViewData["Pare_Id2"] = new SelectList(_context.Schedules
               .Include(s => s.Subject)
               .Include(s => s.PairTime)
               .Where(s => s.Week_Day == Week_Day)
               .Where(s => s.Pair_Time_Id == 2)
               , "Id", "Description");
            ViewData["Pare_Id3"] = new SelectList(_context.Schedules
              .Include(s => s.Subject)
              .Include(s => s.PairTime)
              .Where(s => s.Week_Day == Week_Day)
              .Where(s => s.Pair_Time_Id == 3)
              , "Id", "Description");
            ViewData["Pare_Id4"] = new SelectList(_context.Schedules
              .Include(s => s.Subject)
              .Include(s => s.PairTime)
              .Where(s => s.Week_Day == Week_Day)
              .Where(s => s.Pair_Time_Id == 4)
              , "Id", "Description");
            ViewData["Pare_Id5"] = new SelectList(_context.Schedules
              .Include(s => s.Subject)
              .Include(s => s.PairTime)
              .Where(s => s.Week_Day == Week_Day)
              .Where(s => s.Pair_Time_Id == 5)
              , "Id", "Description");
            ViewData["Pare_Id6"] = new SelectList(_context.Schedules
              .Include(s => s.Subject)
              .Include(s => s.PairTime)
              .Where(s => s.Week_Day == Week_Day)
              .Where(s => s.Pair_Time_Id == 6)
              , "Id", "Description");

            ViewData["Subgroup_Id"] = new SelectList(_context.Subgroups, "Id", "Id");
            return View();
        }

  
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(
            int Pare_Id, 
            int Pare_Id2,
            int Pare_Id3, 
            int Pare_Id4,
            int Pare_Id5,
            int Pare_Id6,
            int Subgroup_Id)

            
        {
            PareSubgroup pareSubgroup = new PareSubgroup { Pare_Id=Pare_Id,Subgroup_Id=Subgroup_Id };
            PareSubgroup pareSubgroup2 = new PareSubgroup { Pare_Id = Pare_Id2, Subgroup_Id = Subgroup_Id };

            PareSubgroup pareSubgroup3 = new PareSubgroup { Pare_Id = Pare_Id3, Subgroup_Id = Subgroup_Id };
            PareSubgroup pareSubgroup4 = new PareSubgroup { Pare_Id = Pare_Id4, Subgroup_Id = Subgroup_Id };

            PareSubgroup pareSubgroup5= new PareSubgroup { Pare_Id = Pare_Id5, Subgroup_Id = Subgroup_Id };
            PareSubgroup pareSubgroup6 = new PareSubgroup { Pare_Id = Pare_Id6, Subgroup_Id = Subgroup_Id };

            if (ModelState.IsValid)
            {
                _context.Add(pareSubgroup);
                _context.Add(pareSubgroup2);
                _context.Add(pareSubgroup3);
                _context.Add(pareSubgroup4);
                _context.Add(pareSubgroup5);
                _context.Add(pareSubgroup6);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Pare_Id"] = new SelectList(_context.Schedules, "Id", "Id", pareSubgroup.Pare_Id);
            ViewData["Pare_Id2"] = new SelectList(_context.Schedules, "Id", "Id", pareSubgroup2.Pare_Id);
            ViewData["Subgroup_Id"] = new SelectList(_context.Subgroups, "Id", "Id", pareSubgroup.Subgroup_Id);
            return View(pareSubgroup);
        }

        // GET: PareSubgroups/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.PareSubgroups == null)
            {
                return NotFound();
            }

            var pareSubgroup = await _context.PareSubgroups.FindAsync(id);
            if (pareSubgroup == null)
            {
                return NotFound();
            }
            ViewData["Pare_Id"] = new SelectList(_context.Schedules, "Id", "Id", pareSubgroup.Pare_Id);
            ViewData["Subgroup_Id"] = new SelectList(_context.Subgroups, "Id", "Id", pareSubgroup.Subgroup_Id);
            return View(pareSubgroup);
        }

        // POST: PareSubgroups/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        

        // GET: PareSubgroups/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.PareSubgroups == null)
            {
                return NotFound();
            }

            var pareSubgroup = await _context.PareSubgroups
                .Include(p => p.Pare)
                .Include(p => p.Subgroup)
                .FirstOrDefaultAsync(m => m.Pare_Id == id);
            if (pareSubgroup == null)
            {
                return NotFound();
            }

            return View(pareSubgroup);
        }

        // POST: PareSubgroups/Delete/5
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> Delete(int id)
        {
            if (_context.PareSubgroups == null)
            {
                return Problem("Entity set 'ApplicationDbContext.PareSubgroups'  is null.");
            }
            var pareSubgroup = _context.PareSubgroups.First(p=>p.Pare_Id == id);
            if (pareSubgroup != null)
            {
                _context.PareSubgroups.Remove(pareSubgroup);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction("Index","Home");
        }

        private bool PareSubgroupExists(int id)
        {
            return (_context.PareSubgroups?.Any(e => e.Pare_Id == id)).GetValueOrDefault();
        }
    }
}

ScheduleProg/Views/PareSubgroups/AdminView.cshtml
@model IEnumerable<ScheduleProg.Models.PareSubgroup>

@{
    ViewData["Title"] = "AdminView";
}

<h1>Index</h1>


<table class="table">
    <thead>
        <tr>
            <th>
                Пара
            </th>
            <th>
               Група
            </th>
             
            
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Pare.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Subgroup.Id)
            </td>
             
        
            <td>
                 <a asp-action="Delete" asp-route-id="@item.Pare.Id">Видалити</a>
            </td>
        </tr>
}
    </tbody>
</table>

ScheduleProg/Views/PareSubgroups/Create.cshtml
@{
    ViewData["Title"] = "Create";
}

<h1>Створити заняття</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post"  action="~/PareSubgroups/Create">
           
            <div class="form-group">
                Пара 1
                <select value="Pare_Id" id="Pare_Id" name="Pare_Id" class ="form-control" asp-items="ViewBag.Pare_Id"></select>
                Пара 2
                <select value="Pare_Id2" id="Pare_Id2" name="Pare_Id2" class ="form-control" asp-items="ViewBag.Pare_Id2"></select>

                Пара 3
                <select value="Pare_Id3" id="Pare_Id3" name="Pare_Id3" class ="form-control" asp-items="ViewBag.Pare_Id3"></select>
                Пара 4
                <select value="Pare_Id4" id="Pare_Id4" name="Pare_Id4" class ="form-control" asp-items="ViewBag.Pare_Id4"></select>

                Пара 5
                <select value="Pare_Id5" id="Pare_Id5" name="Pare_Id5" class ="form-control" asp-items="ViewBag.Pare_Id5"></select>
                Пара 6
                <select value="Pare_Id6" id="Pare_Id6" name="Pare_Id6" class ="form-control" asp-items="ViewBag.Pare_Id6"></select>

                Підгрупа

                <select value="Subgroup_Id" id="Subgroup_Id" name="Subgroup_Id" class ="form-control" asp-items="ViewBag.Subgroup_Id"></select>
           
            </div>
        
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

ScheduleProg/Views/PareSubgroups/Delete.cshtml
@model ScheduleProg.Models.PareSubgroup

@{
    ViewData["Title"] = "Delete";
}

<h1>Видалити заняття</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PareSubgroup</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Pare)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Pare.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Subgroup)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Subgroup.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Pare_Id" />
        <input type="hidden" asp-for="Subgroup_Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ScheduleProg/Views/PareSubgroups/Details.cshtml
@model ScheduleProg.Models.PareSubgroup

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>PareSubgroup</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Pare)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Pare.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Subgroup)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Subgroup.Id)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

ScheduleProg/Views/PareSubgroups/Index.cshtml
@model ScheduleProg.Models.PareSubgroup

@{
    ViewData["Title"] = "Index";
}

<style>
.btn{
padding:20px;
width:20%;
}
.group{
width: 100%;
justify-content: space-between;
display: flex;
}
</style>
<h1>Вибрати день тижня</h1>
<hr />
<div class="row">
    <div class="row">
        <form  method="get" class="group" action="~/PareSubgroups/Create">
        <input type="submit" id="Week_Day" name="Week_Day" value="Понеділок" class="btn btn-primary"></input>
        <input type="submit" id="Week_Day" name="Week_Day" value="Вівторок" class="btn btn-primary"></input>
        <input type="submit" id="Week_Day" name="Week_Day" value="Середа" class="btn btn-primary"></input>
        <input type="submit" id="Week_Day" name="Week_Day" value="Четвер" class="btn btn-primary"></input>
        <input type="submit" id="Week_Day" name="Week_Day" value="П'ятниця" class="btn btn-primary"></input
        </form>
        
       
    </div>
     <div class="row">
        
    
        
       
    </div>
</div>

ScheduleProg/Views/PareSubgroups/SetDate.cshtml
@model ScheduleProg.Models.Pare

@{
    ViewData["Title"] = "";
}

<h1>SetDate</h1>

<h4>Potok</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="GetDay" asp-controller="PareSubgroups">
           <label asp-for="Week_Day" class="control-label"></label>
            <select asp-for="Week_Day" class ="form-control" asp-items="ViewBag.Week_Day"></select>
           
        </form>
         <a asp-action="GetDay">Create</a>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>